# Tensors and operations with TF 2.0

In [2]:
import sys
import shutil
import tensorflow as tf

import numpy as np
%matplotlib inline
import random
import matplotlib.pyplot as plt

In [3]:
# Python version 3.5 or 3.6
assert sys.version_info >= (3, 5)
assert sys.version_info < (3, 7)
# Tensorflow 2.0
assert tf.__version__ >= "2.0"

In this exercise we'll take a look at basic mathemathical operations on tensors.

## Tensors

A tensor is a generalisation a vector or matrix with potentially higher dimentions. TensorFlow manipulates tensors.

Documenentation: https://www.tensorflow.org/guide/tensors

Tensors in TensorFlow are objects of class tf.Tensor() with a type and and shape.

### Constant

In [11]:
# 1-D tensor
tns_1 = tf.constant([1, 2, 3])
tns_1

<tf.Tensor: id=11, shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [9]:
# 2-D tensor
tns_2 = tf.constant([[1, 2, 3], [4, 5, 6]])
tns_2

<tf.Tensor: id=7, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [15]:
# 3-D tensor
tns_3 = tf.constant([[[1, 1], [2, 2], [3, 3], [4, 4]], [[5, 5], [6, 6], [7, 7], [8, 8]]])
tns_3

<tf.Tensor: id=19, shape=(2, 4, 2), dtype=int32, numpy=
array([[[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]],

       [[5, 5],
        [6, 6],
        [7, 7],
        [8, 8]]], dtype=int32)>

#### Attributes

Tensor objects have `dtype` and `shape` attributes.

In [16]:
tns = tf.constant([[1, 2, 3], [4, 5, 6]])

In [ ]:
tsn

In [17]:
tns.dtype

tf.int32

In [ ]:
tns

In [18]:
tns.shape

TensorShape([2, 3])

Type and shape can be defined when instantiating the tensor.

In [20]:
tns = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
tns

<tf.Tensor: id=23, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [23]:
tns = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3, 1))
tns

<tf.Tensor: id=32, shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

#### Accessing tensors

You can access a single element or slices of tensors using indexes within backets.

Index starts at 0.

The `:` notation is used to get all the elements in one dimention. It allows you to access subvectors, submatrices, and even other subtensors.

In [57]:
tns = tf.constant([[1, 2, 3], [4, 5, 6]])

In [ ]:
# Extract element (1, 2)
tns

In [58]:
tns[1, 2]

<tf.Tensor: id=151, shape=(), dtype=int32, numpy=6>

In [ ]:
# Extract first line
tns

In [26]:
tns[0, :]

<tf.Tensor: id=47, shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [24]:
tns[1, 2]

<tf.Tensor: id=37, shape=(1,), dtype=int32, numpy=array([6], dtype=int32)>

#### TF & Numpy

In [45]:
tns = tf.constant([[1, 2, 3], [4, 5, 6]])
tns.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [46]:
np_array = np.array([[1, 2, 3], [4, 5, 6]])
tf.constant(np_array)

<tf.Tensor: id=123, shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

### Variable

A tf.Variable represents a tensor whose value can be changed by running ops on it.

In [32]:
tns = tf.Variable([[1, 2, 3], [4, 5, 6]])
tns

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

### Sparse tensors

TensorFlow represents a sparse tensor as three separate dense tensors: `indices`, `values`, and `dense_shape`. 

* `indices`: A 2-D int64 tensor of dense_shape [N, ndims], which specifies the indices of the elements in the sparse tensor that contain nonzero values (elements are zero-indexed)

* `values`: A 1-D tensor of any type and dense_shape [N], which supplies the values for each element in `indices`. 

* `dense_shape`: A 1-D int64 tensor of dense_shape [ndims], which specifies the dense_shape of the sparse tensor. Takes a list indicating the number of elements in each dimension.

`N` and `ndims` are the number of values and number of dimensions in the SparseTensor, respectively.


Documentation: https://www.tensorflow.org/api_docs/python/tf/sparse/SparseTensor

In [48]:
spr = tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
spr

In [49]:
print(spr)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [51]:
# Get the dense version of a sparse tensor https://www.tensorflow.org/api_docs/python/tf/sparse/to_dense
tf.sparse.to_dense(spr)

<tf.Tensor: id=135, shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]], dtype=int32)>

#### Attributes TODO

## Operations

In [ ]:
tns = tf.constant([[1, 2, 3], [4, 5, 6]])

In [ ]:
# Add a constant
tns

In [ ]:
tns + 1

In [55]:
tns_1 = tf.constant([[1, 2, 3], [4, 5, 6]])
tns_2 = tf.constant([[4, 5, 6], [1, 2, 3]])

In [ ]:
# Addition of tensors
tns_3 = 

In [ ]:
tns_3 = tns_1 + tns_2
tns_3

In [ ]:
# Square of a tensor https://www.tensorflow.org/api_docs/python/tf/math/square

In [ ]:
tns_4 = 

In [41]:
tns_4 = tf.square(tns_1)
tns_4

<tf.Tensor: id=114, shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [ ]:
# Transpose tns_1 https://www.tensorflow.org/api_docs/python/tf/transpose
tns_5 = 

In [42]:
tns_5 = tf.transpose(tns_1)
tns_5

<tf.Tensor: id=117, shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [38]:
# Matrix multiplication https://www.tensorflow.org/api_docs/python/tf/linalg/matmul
# Attention to matrix dimensions
tns_6 = 

In [56]:
tns_6 = tf.matmul(tns_1, tf.transpose(tns_2))
tns_6

<tf.Tensor: id=145, shape=(2, 2), dtype=int32, numpy=
array([[32, 14],
       [77, 32]], dtype=int32)>

### Operations with different types

In [43]:
tns_1 = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
tns_2 = tf.constant([[4, 5, 6], [1, 2, 3]], dtype=tf.float32)

In [44]:
tns_1 + tns_2

InvalidArgumentError: cannot compute Add as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:Add] name: add/

### Operations with sparse tensors TODO

In [ ]:
spr = tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])

In [ ]:
# Add a constant
spr

In [53]:
spr * 10

In [40]:
tns_6 = tf.matmul(tns_1, tf.transpose(tns_2))
tns_6

<tf.Tensor: id=112, shape=(2, 2), dtype=int32, numpy=
array([[32, 14],
       [77, 32]], dtype=int32)>

In [37]:
tns_4 = tf.transpose(tns_1)
tns_4

<tf.Tensor: id=108, shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [36]:
tns_3 = tns_1 + tns_2
tns_3

<tf.Tensor: id=105, shape=(2, 3), dtype=int32, numpy=
array([[5, 7, 9],
       [5, 7, 9]], dtype=int32)>

In [ ]:
tns + 1